### ISSUE TITLE
fix: When deploying to globe getting issue as: A directory corresponding to fileSystemPath "public" could not be found

### ISSUE THREAD

**Issue by komiljonovshohjahon** [VeryGoodOpenSource/dart_frog#1275]
**Description**

Cannot deploy to [Globe](globe.dev) with public folder included.

**Steps To Reproduce**

When deployed without public folder, works fine.
But when deployed with public folder, getting issue as Invalid argument(s): A directory corresponding to fileSystemPath "public" could not be found.

**Expected Behavior**

--------

**Additional Context**

Full log from Globe build log:

22:39:05.220
Start the production server by running:
22:39:05.221
22:39:05.221
dart build/bin/server.dart
22:39:05.390
22:39:05.390
Compiling entrypoint "/workspace/archive/build/bin/server.dart"...
22:39:05.390
Running command: dart compile exe /workspace/archive/build/bin/server.dart -o /workspace/archive/.globe_build/dc10cbf6-04b6-4021-9ebc-564cec0fb182.exe --verbosity=warning
22:39:05.391
22:39:10.109
Generated: /workspace/archive/.globe_build/dc10cbf6-04b6-4021-9ebc-564cec0fb182.exe
22:39:10.143
Successfully completed step BUILD.
22:39:10.143
Step BUILD took 31961ms
22:39:10.934
Starting step VERIFY.
22:39:12.411
Failed to verify deployment. Status: 503
22:39:12.411
Unhandled exception:
22:39:12.411
Invalid argument(s): A directory corresponding to fileSystemPath "public" could not be found
22:39:12.411
#0 createStaticHandler (package:shelf_static/src/static_handler.dart:50)
22:39:12.411
#1 createStaticFileHandler (package:dart_frog/src/create_static_file_handler.dart:7)
22:39:12.411
#2 createServer (file:///workspace/archive/build/bin/server.dart:19)
22:39:12.411
#3 main (file:///workspace/archive/build/bin/server.dart:15)
22:39:12.411
#4 _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
22:39:12.411
#5 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
22:39:12.411
22:39:12.411
{
22:39:12.411
"code": "exit",
22:39:12.411
"description": "Process exited.",
22:39:12.411
"trace": "unknown:7543089f22c298ffb766a4d90de6f8c3",
22:39:12.411
"time": "2024-01-31T17:39:12.383830Z",
22:39:12.411
"exit_code": "255"
22:39:12.412
}
22:39:12.414
Step VERIFY took 1479ms
22:39:12.414
Step VERIFY failed.

**Comment by wolfenrain** [comment]
I presume Globe is controlling the build of the Dart Frog instance, you guys have some insights on that @salakar @ehesp?

**Comment by Ehesp** [comment]
This looks like it's stemming from `createStaticHandler` from Shelf. @komiljonovshohjahon have you added this yourself, or is Dart Frog handling static assets using that middleware?

**Comment by komiljonovshohjahon** [comment]
@Ehesp I did not add anything.
Dart Frog handles itself. I just wanted to serve my few static files with Dart Frog API.

**Comment by komiljonovshohjahon** [comment]
It may be happening from the Globe side, or something.
So I also opened an issue at the same time as this issue.
https://github.com/invertase/globe/issues/38

**Comment by alestiago** [comment]
Closing in favour of https://github.com/invertase/globe/issues/38
