### ISSUE TITLE
fix: dart_frog dev -H

### ISSUE THREAD

**Issue by MikeRaschend** [VeryGoodOpenSource/dart_frog#1294]
With dart_frog dev works everything fine, but
if i use my own server IP with option -H
then i get the output:
(i hide my ip with ****)

dart_frog dev -H ****
✓ Running on http://****:8080 (0.8s)
The Dart VM service is listening on http://127.0.0.1:8181/AyLFVYgiJDA=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/AyLFVYgiJDA=/devtools?uri=ws://127.0.0.1:8181/AyLFVYgiJDA=/ws
[hotreload] Hot reload is enabled.
Press either R or r to reload
Unhandled exception:
SocketException: Failed to create server socket (OS Error: Cannot assign requested address, errno = 99), address = ****, port = 8080
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1032:7)
<asynchronous suspension>
#1      _RawServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:1812:15)
<asynchronous suspension>
#2      _ServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2097:15)
<asynchronous suspension>
#3      _HttpServer.bind.<anonymous closure> (dart:_http/http_impl.dart:3186:27)
<asynchronous suspension>
#4      serve (package:shelf/shelf_io.dart:60:16)
<asynchronous suspension>
#5      withHotreload.<anonymous closure> (package:shelf_hotreload/src/with_hotreload.dart:81:21)
<asynchronous suspension>
#6      withHotreload (package:shelf_hotreload/src/with_hotreload.dart:102:3)
<asynchronous suspension>
[process] Server process has been terminated

**Comment by MikeRaschend** [comment]
my mistake, wrong ip adress
