### ISSUE TITLE
fix: getIt hot reload Error

### ISSUE THREAD

**Issue by tyypgzl** [VeryGoodOpenSource/dart_frog#482]
**Description**

I create any class with getIt. but where do i need to use setUp Function? When I use it inside the run() function, I get a hot reload error.

- main.dart
```dart
Future<HttpServer> run(Handler handler, InternetAddress ip, int port) {
  setup();

  return serve(handler, ip, port);
}
```

- locator.dart
```dart
import 'package:get_it/get_it.dart';
import 'package:notify/utils/env.dart';

final getIt = GetIt.instance;

void setup() {
  getIt.registerSingleton<Env>(Env());
}
```

- Exception
```text
Unhandled exception:
Invalid argument(s): Object/factory with  type Env is already registered inside GetIt. 
#0      throwIf (package:get_it/get_it_impl.dart:7:18)
#1      _GetItImplementation._register (package:get_it/get_it_impl.dart:803:5)
#2      _GetItImplementation.registerSingleton (package:get_it/get_it_impl.dart:587:5)
#3      setup (package:notify/locator/locator.dart:7:9)
#4      run (file:///Users/tayyipguzel/Desktop/dev/personal/notify/server/main.dart:8:3)
#5      createServer (file:///Users/tayyipguzel/Desktop/dev/personal/notify/server/.dart_frog/server.dart:22:21)
#6      withHotreload.<anonymous closure> (package:shelf_hotreload/src/with_hotreload.dart:81:33)
<asynchronous suspension>
```

- Maybe we needed a function that we could do initialization but not wrapped with the hotReload() function.

**Comment by GabrielRozendo** [comment]
#335

**Comment by exaby73** [comment]
A workaround is to call `getIt.reset()` on the first line if `setup()`

**Comment by alestiago** [comment]
Thanks @tyypgzl for opening an issue!

Dart Frog now supports a custom init method. Does using it resolve this issue? 

Documentation about the custom init method can be found [here](https://dartfrog.vgv.dev/docs/advanced/custom_init_method).

**Comment by alestiago** [comment]
Closing this due to inactivity from original contributor. Feel free to re-open if you think this [solution](https://github.com/VeryGoodOpenSource/dart_frog/issues/482#issuecomment-1497413145) don't fix the issue.

**Comment by alestiago** [comment]
Closing this due to inactivity from original contributor. Feel free to re-open if you think this [solution](https://github.com/VeryGoodOpenSource/dart_frog/issues/482#issuecomment-1497413145) don't fix the issue.
